# Dockerfile.frontend
FROM base AS build
WORKDIR /usr/src/app/frontend
COPY ./home-automation-frontend/package*.json ./
RUN npm install
COPY ./home-automation-frontend ./
RUN npm run build

FROM nginx:alpine
COPY --from=build /usr/src/app/frontend/dist/home-automation-frontend /usr/share/nginx/html
VOLUME /etc/letsencrypt
EXPOSE 80 443
